### PR TITLE
Optimised PNG

### PR DESCRIPTION
**Pull request by coliff**
Optimised using PNGGauntlet, Losslessly reduced file size to 77% of
original size.

### CODE REVIEW

**Comment by anselmh** [comment]
LGTM.

**Comment by anselmh** [comment]
Oh, please always do one feature at a time in a PR. Can you strip the latest commit as we have a separate PR on that issue already? Then I can merge it :)

**Comment by coliff** [comment]
@anselmh - sorry about that. I reverted the change and will do a separate PR for that.

**Comment by anselmh** [comment]
Thanks again for this PR. The title thing is already in by now but thanks for helping out here :)

**Comment by coliff** [comment]
Cool. Saw you added that. :-)

**Pull request merged**
